ALTER TABLE installs DROP CONSTRAINT IF EXISTS insoft;
ALTER TABLE installs DROP CONSTRAINT IF EXISTS inpcs;
ALTER TABLE pcs DROP CONSTRAINT IF EXISTS room;
ALTER TABLE rooms DROP CONSTRAINT IF EXISTS roomsemp; 

ALTER TABLE installs ADD CONSTRAINT insoft FOREIGN KEY (soft_id) REFERENCES soft (id); 

ALTER TABLE installs ADD CONSTRAINT inpcs FOREIGN KEY (pc_id) REFERENCES pcs (id);

ALTER TABLE pcs ADD CONSTRAINT room FOREIGN KEY (room_id) REFERENCES rooms (id); 

ALTER TABLE rooms ADD CONSTRAINT roomsemp FOREIGN KEY (emp_id) REFERENCES employees (id);  
